config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  devise_for :users

  resources :users
  get 'users/:id/account', to: 'users#account'
  resources :flashcards do 
    member do 
      post 'add'
      post 'add_list'
      delete 'remove'
      get 'remove_list'
    end 
    collection do 
      get 'grid'
      get 'list'
      post "bulk"
    end 
  end 

  resources :user do 
    resources :decks do 
      member do 
        post 'add_flashcard'
        delete 'remove_flashcard'
      end 

      collection do 
        get 'check_deck_flashcards'
      end 
      resources :deck_flashcards, only: [:show, :update] do 
        member do
          post :mark_correct
          post :mark_incorrect
        end
      end
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "flashcards#index"

  get 'contact', to: 'contact#show'
end

app/models/flashcard.rb
# == Schema Information
#
# Table name: flashcards
#
#  id         :bigint           not null, primary key
#  back       :string           not null
#  front      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Flashcard < ApplicationRecord
  has_many :deck_flashcards, dependent: :destroy

  validates :front, presence: true 
  validates :back, presence: true

  scope :search, -> (params = {}) {
    if params[:front]
      search_term = params[:front].downcase
      where("lower(front) LIKE ?", "%#{search_term}%")
    else
      all
    end
  }

  scope :sorted_by, -> (sort_order) {
    case sort_order 
    when "front_asc"
      order(front: :asc)
    when "front_desc"
      order(front: :desc)
    when "back_asc"
      order(back: :asc)
    when "back_desc"
      order(back: :desc)
    end
  }
end

app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController
  
  before_action :set_flashcard, except: [:index, :grid, :list, :bulk]
  # before_action :set_flashcard_statistic, except: [:index]


  def index  
    @pagy, @flashcards = pagy(Flashcard.search(params).sorted_by(params[:sort]))
    @deck = current_user.deck
  end
  

  def show
  end

  def edit 
    
  end

  def update 
    if @flashcard.update(flashcard_params) 
      flash[:success] = "Flashcard sucessfully updated"
      redirect_to @flashcard 
    else  
      flash[:error] = "Something went wrong"
      redirect_to edit_flashcard_path 
    end
  end

  def grid
    @flashcards = Flashcard.search(params)
    respond_to do |format|
      format.html { render partial: 'flashcards/grid_view', locals: { flashcards: @flashcards } }
      format.js   # if you have grid.js.erb
    end
  end
  
  #WHat is this used for?
  def list
    @pagy, @flashcards = pagy(Flashcard.search(params))
    respond_to do |format|
      format.html { render partial: 'flashcards/list_view', locals: { flashcards: @flashcards } }
      format.js   # if you have list.js.erb
    end
  end

  def add 
    @deck = current_user.deck 
    @deck.add_flashcard(@flashcard)

    flash.now[:notice] = "Flashcard \"#{@flashcard.front}\" added to Deck"
    
    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end 

  def remove 
    @deck = current_user.deck 
    @deck.remove_flashcard(@flashcard)

    flash.now[:notice] = "Flashcard \"#{@flashcard.front}\" removed from Deck"
    
    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end 

  # def add_list
  #   @deck = current_user.deck 
  #   @deck.add_flashcard(@flashcard)

  #   flash.now[:notice] = "Flashcard \"#{@flashcard.front}\" added to Deck"
    
  #   respond_to do |format|
  #     format.turbo_stream
  #     format.html
  #   end 
  # end 

  # def remove_list 
  #   @deck = current_user.deck 
  #   @deck.remove_flashcard(@flashcard)

  #   flash.now[:notice] = "Flashcard \"#{@flashcard.front}\" removed from Deck"
    
  #   respond_to do |format|
  #     format.turbo_stream
  #     format.html
  #   end
  # end 

  def bulk 
    operation = params[:operation]
    selected_flashcard_ids = params[:selected_flashcards]
    unless selected_flashcard_ids.nil?
      @deck = current_user.deck 
      @deck.update_flashcards(selected_flashcard_ids, operation)
    end

    @flashcards = Flashcard.all

    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end

  def destroy 
    if @flashcard.destroy 
      flash[:success] = "Flashcard was successfully deleted"
      redirect_to flashcards_path
    else  
      flash[:error] = "There was a problem deleting the flashcard"
      redirect_to @flashcard 
    end
  end 

  private

  def set_flashcard
    @flashcard = Flashcard.find_by(id: params[:id])
    redirect_to root_path, alert: "Flashcard not found" if @flashcard.nil?
  end 

  def flashcard_params
    params.require(:flashcard).permit(:front, :back)
  end
end

app/helpers/flashcards_helper.rb
module FlashcardsHelper
end

app/views/flashcards/_dropdown.html.erb
<!--
  This example requires some changes to your config:
  
  ```
  // tailwind.config.js
  module.exports = {
    // ...
    plugins: [
      // ...
      require('@tailwindcss/forms'),
    ],
  }
  ```
-->
<div>
  <label for="operation" class="block text-sm font-medium leading-6 text-gray-900"></label>
  <select id="operation" name="operation" class="mt-2 block w-full rounded-md border-0 py-1.5 pl-3 pr-10 text-gray-900 ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-indigo-600 sm:text-sm sm:leading-6">
    <option>Add selection</option>
    <option selected>Remove selection</option>
  </select>
</div>

app/views/flashcards/_flashcard.html.erb
<%= turbo_frame_tag dom_id(flashcard) do%>

    <div id="search_results" class="flex-col">

    <!-- Checkbox -->
    <input type="checkbox" class="" id="checkbox_<%= flashcard.id %>" name="selected_flashcards[]" data-cbox-all-target="checkbox">
    <label for="checkbox_<%= flashcard.id %>" class="absolute top-0 right-0 mt-4 mr-4"></label>

    <a
      data-turbo-frame = "_top"
      class="block max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700"
    >
      <h5
        class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"
      >
      <%= flashcard.front %>
      </h5>
      <p class="font-normal text-gray-700 dark:text-gray-400">
        <%= flashcard.back %>
      </p>
    </a>
    <!-- -->


    <% if current_user %>
      <% if current_user.deck.deck_flashcards.exists?(flashcard_id: flashcard.id) %>
        <%= button_to 'Remove from Deck', remove_flashcard_path(flashcard.id), class: "rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600", method: :delete %>
      <% else %>
        <%= button_to 'Add to Deck', add_flashcard_path(flashcard.id), class: "rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600", method: :post %>
      <% end %>
    <% end %>

    <%= link_to "Flashcard Details", flashcard_path(flashcard), data: {turbo_frame: "_top"} %>
    </div>
  <% end %>

app/views/flashcards/_flashcardpanel.html.erb
<%= turbo_frame_tag 'flashcardicon'  do%>
<div class="flex">
  <a class="bg-gray-800 text-white rounded-l-md border-r border-gray-100 py-2 hover:bg-red-700 hover:text-white px-3" 
  href="<%= @prev_id ? flashcard_path(@prev_id) : flashcard_path(@flashcard.id) %>" data-turbo-frame="flashcardicon">
    <div>
      <div class="flex flex-row align-middle">
        <svg
          class="w-5 mr-2"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M7.707 14.707a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l2.293 2.293a1 1 0 010 1.414z"
            clip-rule="evenodd"
          ></path>
        </svg>
        
        <p class="ml-2">Prev</p>
      </div>
    </div>
  </a>

  
  <section id="flashcardicon">
    <a
      href="<%= flashcard_path(@flashcard.id) %>"
      class="block max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700"
    >
      <h5
        class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"
      >
      <%= @flashcard.front %>
      </h5>
      <p class="font-normal text-gray-700 dark:text-gray-400">
        Here are the biggest enterprise technology acquisitions of 2021 so far,
        in reverse chronological order.
      </p>
    </a>
  </section>
 

  <a class="bg-gray-800 text-white rounded-r-md py-2 border-l border-gray-200 hover:bg-red-700 hover:text-white px-3"
  href="<%= @next_id ? flashcard_path(@next_id) : flashcard_path(@flashcard.id) %>" data-turbo-frame="flashcardicon" >
    <div>
      <div class="flex flex-row align-middle">
        <span class="mr-2">Next</span>
        <svg
          class="w-5 ml-2"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M12.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-2.293-2.293a1 1 0 010-1.414z"
            clip-rule="evenodd"
          ></path>
        </svg>
      </div>
    </div>
    </a>
</div>

<div class="flex justify-center pt-6 gap-2">
  <button type="button" class="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Correct</button>
  <button type="button" class="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Incorrect</button>
</div>

<div class="flex flex-col items-center justify-center pt-6 gap-2">
  <h2>Stats</h2>
  <p>Correct: </p>
  <p>Incorrect: </p>
</div>
<% end %>

app/views/flashcards/_grid_view.html.erb
<%= turbo_frame_tag 'results'  do %>
  <%= render "tableicons" %>
  <%= render "search", form_url: grid_flashcards_path %> <!-- Note the checkbox wraps from here -->
    <div class="flex flex-wrap gap-2 mt-8 justify-center">
    <% @flashcards.each do |flashcard| %>
      <%= render flashcard %>
    <% end %>
  </div>
<% end %>

app/views/flashcards/_line_item.html.erb
<div class="table-row" id=<%= dom_id(flashcard)%>>
  <div class="table-cell whitespace-nowrap px-3 py-4 text-sm">
    <%= check_box_tag "selected_flashcards[]", flashcard.id, false, data: { cbox_all_target: "checkbox" } %>
  </div>
  <div class="table-cell whitespace-nowrap py-4 pl-4 pr-3 text-sm text-gray-500 sm:pl-0"><%= flashcard.front %></div>
  
  <div class="table-cell whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= flashcard.back %></div>
  <div class="font-medium text-blue-600 dark:text-blue-500 hover:underline"><%= link_to "Details", flashcard_path(flashcard), data: {turbo_frame: "_top"}%></div>
  <div class="table-cell relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-0">
  <% if current_user.deck.deck_flashcards.exists?(flashcard_id: flashcard.id)%>
    In Deck
  <% else %>
    Not in Deck
  <% end %>
  </div>
</div>

app/views/flashcards/_list_view.html.erb
<%= turbo_frame_tag 'results' do %>
  <%= render "tableicons" %>
  <%= render "search"%> <!-- Note the checkbox wraps from here -->
<% end %>

app/views/flashcards/_search.html.erb
<%= simple_form_for("", url: flashcards_path , method: :get, 
    html: { 
      "data-controller": "form", 
      "data-action": "input->form#submit" }
    ) do |f| %>
    <!-- removed turbo advance because bugs. Add later" -->
  <div class="flex justify-center gap-2">
    <div>
      <%= f.input :front, label: false, input_html: { placeholder: 'Name...', value: params[:front] } %>
    </div>
    <div>
      <%= f.input :sort_by, label: false, as: :select, collection: [['Highest Accuracy', 'highest_accuracy'], ['Lowest Accuracy', 'lowest_accuracy'], ['Name', 'name']], prompt: "Sort By", selected: params[:sort_by] %>
    </div>
    <div class="flex align-center">
      <%= f.button :submit, "Search" %>
    </div>
  </div>
<% end %>

<%= form_with url:bulk_flashcards_path, model: @flashcard, data: { controller: 'cbox-all' } do |f| %>
  <legend class="sr-only">Select All</legend>
  <div class="space-y-5">
    <div class="relative flex justify-center items-start gap-2">
      <div class="flex h-6 items-center">
        <input id="comments" aria-describedby="comments-description" name="comments" type="checkbox" class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-600" data-cbox-all-target="checkboxAll">
      </div>
      
      <div class="ml-3 text-sm leading-6">
        <label for="comments" class="font-medium text-gray-900">Select All</label>
      </div>
      <div>
        <%= render "dropdown"%>
      </div>
    </div>
  </div>

  <!-- #div from checkbox -->
  <!-- list view -->
  <div class="px-4 sm:px-6 lg:px-8">
    <div class="mt-1 flow-root">
      <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
          <div class="table min-w-full divide-y divide-gray-300">
            <div class="table-header-group">
              <div class="table-row">
                <div class="table-cell py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Select</div>
                <div class="table-cell py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">
                  <div class="flex items-center">
                    <% if params[:sort] == "front_asc" %>
                      <svg class="h-4 w-4 text-black"  width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  <path stroke="none" d="M0 0h24v24H0z"/>  <line x1="12" y1="5" x2="12" y2="19" />  <line x1="16" y1="9" x2="12" y2="5" />  <line x1="8" y1="9" x2="12" y2="5" /></svg>
                      <%= link_to "English", flashcards_path(sort: 'front_desc')%>
                    <% elsif params[:sort] == "front_desc"  %>
                      <svg class="h-4 w-4 text-black"  width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  <path stroke="none" d="M0 0h24v24H0z"/>  <line x1="12" y1="5" x2="12" y2="19" />  <line x1="16" y1="15" x2="12" y2="19" />  <line x1="8" y1="15" x2="12" y2="19" /></svg>
                      <%= link_to "English", flashcards_path(sort: 'front_asc')%>
                    <% else %>
                     <%= link_to "English", flashcards_path(sort: 'front_asc')%>
                    <% end %>
                  </div>
                </div>
                <div class="table-cell px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
                  <div class="flex items-center">
                    <% if params[:sort] == "back_asc" %>
                      <svg class="h-4 w-4 text-black"  width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  <path stroke="none" d="M0 0h24v24H0z"/>  <line x1="12" y1="5" x2="12" y2="19" />  <line x1="16" y1="9" x2="12" y2="5" />  <line x1="8" y1="9" x2="12" y2="5" /></svg>
                      <%= link_to "Portuguese", flashcards_path(sort: 'back_desc')%>
                    <% elsif params[:sort] == "back_desc" %>
                      <svg class="h-4 w-4 text-black"  width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  <path stroke="none" d="M0 0h24v24H0z"/>  <line x1="12" y1="5" x2="12" y2="19" />  <line x1="16" y1="15" x2="12" y2="19" />  <line x1="8" y1="15" x2="12" y2="19" /></svg>
                      <%= link_to "Portuguese", flashcards_path(sort: 'back_asc')%>
                    <% else %>
                      <%= link_to "Portuguese", flashcards_path(sort: 'back_asc')%>
                    <% end %>
                  </div>
                </div>
                <div class="table-cell relative py-3.5 pl-3 pr-4 sm:pr-0">
                  <span class="sr-only">In Deck?</span>
                </div>
              </div>
            </div>
            <div class="table-row-group divide-y divide-gray-200">
            <% @flashcards.each do |flashcard| %>
              <%= render "line_item", flashcard: flashcard  %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>


  <%= f.submit "Submit" %>
<% end %>

<%== pagy_nav(@pagy) %>

app/views/flashcards/_tableicons.html.erb
<div class="bg-gray-200 text-sm text-gray-500 leading-none border-2 border-gray-200 rounded-full inline-flex">
  <%= link_to "#", id: 'grid', class: "inline-flex items-center transition-colors duration-300 ease-in focus:outline-none hover:text-blue-400 focus:text-blue-400 rounded-l-full px-4 py-2  #{'active' if current_page?(grid_flashcards_path)} " do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="fill-current w-4 h-4 mr-2"><rect x="3" y="3" width="7" height="7"></rect><rect x="14" y="3" width="7" height="7"></rect><rect x="14" y="14" width="7" height="7"></rect><rect x="3" y="14" width="7" height="7"></rect></svg>
    <span>Grid</span>
  <% end %>
  
  <%= link_to list_flashcards_path, id: 'list', class: "inline-flex items-center transition-colors duration-300 ease-in focus:outline-none hover:text-blue-400 focus:text-blue-400 rounded-r-full px-4 py-2 #{'active' if current_page?(list_flashcards_path) || current_page?(flashcards_path) || current_page?(root_path)}" do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="fill-current w-4 h-4 mr-2"><line x1="8" y1="6" x2="21" y2="6"></line><line x1="8" y1="12" x2="21" y2="12"></line><line x1="8" y1="18" x2="21" y2="18"></line><line x1="3" y1="6" x2="3.01" y2="6"></line><line x1="3" y1="12" x2="3.01" y2="12"></line><line x1="3" y1="18" x2="3.01" y2="18"></line></svg>
    <span>List</span>
  <% end %>
</div>

<style>
  /*@apply bg-white text-blue-400 rounded-full;*/
  .active {background: white; border-radius: 9999px; color: #63b3ed;}
</style>
<!--End of Grid view & List view -->

app/views/flashcards/add.turbo_stream.erb
<%= turbo_stream.replace(dom_id(@flashcard)) do%>
  <%= render partial: "flashcards/flashcard", locals: {flashcard: @flashcard} %>
<%end%>

<%= turbo_stream.replace "flash", partial: "layouts/flash" %>

app/views/flashcards/bulk.turbo_stream.erb
<%= turbo_stream.replace "flash", partial: "layouts/flash" %>


<% @flashcards.each do |flashcard| %>
  <% if dom_id(flashcard).nil? %>
    <%= turbo_stream.append dom_id(flashcard), partial: "flashcards/line_item", locals: {flashcard: flashcard}%>
  <% else %>
    <%= turbo_stream.replace dom_id(flashcard), partial: "flashcards/line_item", locals: {flashcard: flashcard} %>
  <% end %>
<% end %>

app/views/flashcards/edit.html.erb
<%= form_with model: @flashcard do |form| %>
  <%= form.text_field :front %>
  <%= form.text_field :back %>
  <%= form.submit %>
<% end %>

app/views/flashcards/index.html.erb
<%= render "list_view" %>

app/views/flashcards/remove.turbo_stream.erb
<%= turbo_stream.replace(dom_id(@flashcard)) do%>
  <%= render partial: "flashcards/flashcard", locals: {flashcard: @flashcard} %>
<%end%>

<%= turbo_stream.replace "flash", partial: "layouts/flash" %>

app/views/flashcards/show.html.erb
<div class="flex-col">
<div>THis is the cards details page for <%= @flashcard.front %></div>
<br>
<div class="font-medium text-blue-600 dark:text-blue-500 hover:underline"><%= link_to "Return to Flashcards", flashcards_path %></div>
</div>
<br>
<div class="flex flex-col">
  <div>Admin:</div>
  <div>
   <%= link_to "Edit", edit_flashcard_path(@flashcard),class: "font-medium text-blue-600 dark:text-blue-500 hover:underline" %>
  </div>
  <Div>
<%= button_to "Destroy", flashcard_path(@flashcard), method: :delete, data: { turbo_confirm: "Are you sure?"}, class: "font-medium text-blue-600 dark:text-blue-500 hover:underline" %>

  </Div>
</div>