config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  devise_for :users

  resources :users
  get 'users/:id/account', to: 'users#account'
  resources :flashcards do 
    member do 
      post 'add'
      post 'add_list'
      delete 'remove'
      get 'remove_list'
    end 
    collection do 
      get 'grid'
      get 'list'
      post "bulk"
    end 
  end 

  resources :user do 
    resources :decks do 
      member do 
        post 'add_flashcard'
        delete 'remove_flashcard'
      end 

      collection do 
        get 'check_deck_flashcards'
      end 
      resources :deck_flashcards, only: [:show, :update] do 
        member do
          post :mark_correct
          post :mark_incorrect
        end
      end
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "flashcards#index"

  get 'contact', to: 'contact#show'
end

app/models/deck.rb
# == Schema Information
#
# Table name: decks
#
#  id                    :bigint           not null, primary key
#  average_accuracy      :float            default(0.0), not null
#  total_attempts        :integer          default(0), not null
#  total_correct_count   :integer          default(0), not null
#  total_incorrect_count :integer          default(0), not null
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  user_id               :bigint           not null
#
# Indexes
#
#  index_decks_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Deck < ApplicationRecord
  belongs_to :user
  has_many :deck_flashcards

  # NOTE: You don't need this. ActiveRecord enforces relationships for you automatically.
  # validates :user_id, presence: true, numericality: { only_integer: true }
  validates :total_correct_count,
            :total_incorrect_count, 
            :total_attempts,
            presence: true, 
            numericality: { 
              only_integer: true, 
              greater_than_or_equal_to: 0 
            }
  validates :average_accuracy, 
            presence: true, 
            numericality: { 
              only_float: true, 
              greater_than_or_equal_to: 0, 
              less_than_or_equal_to: 1
            }


  def add_flashcard(flashcard)
    self.deck_flashcards.create(flashcard_id: flashcard.id)
  end 

  def remove_flashcard(flashcard)
    deck_flashcard = self.deck_flashcards.find_by(flashcard: flashcard)
    deck_flashcard.destroy
  end 

  def add_flashcards(flashcards)
    flashcards.each do |flashcard| 
      flashcardid = flashcard.to_i
      if self.deck_flashcards.find_by(flashcard_id: flashcardid).nil?
        self.add_flashcard(Flashcard.find(flashcardid))
      end
    end 
  end 

  def update_flashcards(flashcards, operation)
    if operation == "Add selection"
      flashcards.each do |flashcard| 
        flashcardid = flashcard.to_i
        if self.deck_flashcards.find_by(flashcard_id: flashcardid).nil?
          self.add_flashcard(Flashcard.find(flashcardid))
        end
      end 
    elsif operation == "Remove selection"
      flashcards.each do |flashcard| 
        flashcardid = flashcard.to_i
        unless self.deck_flashcards.find_by(flashcard_id: flashcardid).nil?
          self.remove_flashcard(Flashcard.find(flashcardid))
        end
      end 
    end 
  end 
  
  def update_statistics
    if self.deck_flashcards.exists?
      update_counts
      update_average_accuracy
    else  
      reset_statistics
    end 
  end

  private 

  def update_counts 
    self.total_correct_count = self.deck_flashcards.total_correct_count
    self.total_incorrect_count = self.deck_flashcards.total_incorrect_count
    save
  end 

  def update_average_accuracy
    average_accuracy = self.total_correct_count / (self.total_correct_count.to_f + self.total_incorrect_count )
    self.average_accuracy = average_accuracy.nan? ? 0 : average_accuracy
    save
  end  

  #Improvement - analyze later
  # def update_average_accuracy
  #   denominator = (total_correct_count + total_incorrect_count ).to_f

  #   if denominator.zero?
  #     update(average_accuracy: 0)
  #   else
  #     update(average_accuracy: total_correct_count / denominator)
  #   end
  # end  

  def reset_statistics
    self.total_correct_count = 0
    self.total_incorrect_count = 0
    self.average_accuracy = 0.0
    save
  end 
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController

  before_action :set_deck, except: :check_deck_flashcards
  before_action :set_flashcard, only: [:add_flashcard, :remove_flashcard]

  def check_deck_flashcards
    if current_user.deck.deck_flashcards.empty?
      redirect_to root_path, alert: "Please add flashcards to your deck to start studying."
    else  
      # Redirects to study page
      # This needs to be refactored
      # Business logic to determine the order of flashcards belongs in a model
      redirect_to user_deck_deck_flashcard_path(current_user, current_user.deck, current_user.deck.deck_flashcards.first.id)
    end 
  end 

  def show 
    authorize @deck
    @category = params[:category]
    @categorized_deck_flashcards = @deck.deck_flashcards.by_category(@category)

    respond_to do |format|
      format.turbo_stream
      format.html 
    end
  end

  def add_flashcard 
    authorize @deck
    @deck.add_flashcard(@flashcard)

    flash.now[:notice] = "Flashcard \"#{@flashcard.front}\" added to Deck"
    
    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end 

  def remove_flashcard 
    authorize @deck
    @deck_flashcard = DeckFlashcard.find(params[:deck_flashcard_id])
    @deck_flashcard_id = @deck_flashcard.id 
    @deck_flashcard.destroy
    
    flash.now[:notice] = "Flashcard \"#{@flashcard.front}\" removed from Deck"

    @deck = current_user.deck
    @category = params[:category]
    @categorized_deck_flashcards = @deck.deck_flashcards.by_category(@category)
    
    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end

  private 

  def set_deck 
    @deck = current_user.deck
  end 

  def set_flashcard 
    @flashcard = Flashcard.find(params[:flashcard_id].to_i)
  end

end

app/helpers/decks_helper.rb
module DecksHelper
  def user_deck_classes(category=nil)
    default = "rounded-full px-4 py-2.5 text-sm font-semibold shadow-sm ring-1 ring-inset ring-gray-300"
    active = "bg-green-500 text-white hover:text-black hover:bg-green-500"
    inactive = "bg-white text-gray-900 hover:bg-gray-50"
    
    params[:category] == category ? default + " " + active : default + " " + inactive
  end
end

app/views/decks/_stats.html.erb
<div class="overflow-hidden rounded-lg bg-white shadow">
    <%# <div class="px-4 py-5 sm:p-6">
      Deck name | deck count | deck accuracy
    </div> %>
    <dl class="mx-auto grid grid-cols-1 gap-px bg-gray-900/5 sm:grid-cols-2 lg:grid-cols-4">
      <div class="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-2 bg-white px-4 py-10 sm:px-6 xl:px-8">
        <dt class="text-sm font-medium leading-6 text-gray-500">Total cards</dt>
        <dd class="text-xs font-medium text-gray-700"></dd>
        <dd class="w-full flex-none text-3xl font-medium leading-10 tracking-tight text-gray-900"><%= @categorized_flashcards.size %></dd>
      </div>
      <div class="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-2 bg-white px-4 py-10 sm:px-6 xl:px-8">
        <dt class="text-sm font-medium leading-6 text-gray-500">Correct count</dt>
        <dd class="text-xs font-medium text-rose-600"></dd>
        <dd class="w-full flex-none text-3xl font-medium leading-10 tracking-tight text-gray-900"><%= @correct_count %></dd>
      </div>
      <div class="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-2 bg-white px-4 py-10 sm:px-6 xl:px-8">
        <dt class="text-sm font-medium leading-6 text-gray-500">Incorrect count</dt>
        <dd class="text-xs font-medium text-gray-700"></dd>
        <dd class="w-full flex-none text-3xl font-medium leading-10 tracking-tight text-gray-900"><%= @incorrect_count %></dd>
      </div>
      <div class="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-2 bg-white px-4 py-10 sm:px-6 xl:px-8">
        <dt class="text-sm font-medium leading-6 text-gray-500">Accuracy</dt>
        <dd class="text-xs font-medium text-rose-600"></dd>
        <dd class="w-full flex-none text-3xl font-medium leading-10 tracking-tight text-gray-900"><%= @accuracy %>%</dd>
      </div>
    </dl>
  </div>

app/views/decks/_stats_body.html.erb
<div class="px-4 sm:px-6 lg:px-8">
  <div class="mt-1 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <div class="table min-w-full divide-y divide-gray-300">
          <div class="table-header-group">
            <div class="table-row">
              <div class="table-cell py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Front</div>
              <div class="table-cell px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Back</div>
              <div class="table-cell px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Correct</div>
              <div class="table-cell px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Incorrect</div>
              <div class="table-cell px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Accuracy</div>
              <%# <div class="table-cell relative py-3.5 pl-3 pr-4 sm:pr-0">
                <span class="sr-only">Edit</span>
              </div> %>
               <div class="table-cell px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Actions</div>
            </div>
          </div>
          <div class="table-row-group divide-y divide-gray-200">
            <% @categorized_deck_flashcards.each do |deck_flashcard| %>

              <div class="table-row" id=<%= dom_id(deck_flashcard) %>>
                <div class="table-cell whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0"><%= deck_flashcard.flashcard.front %></div>
                <div class="table-cell whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= deck_flashcard.flashcard.back %></div>
                <div class="table-cell whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= deck_flashcard.correct_count %></div>
                <div class="table-cell whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= deck_flashcard.incorrect_count %></div>
                <div class="table-cell whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= deck_flashcard.accuracy.round(0) %>%</div>
                <div class="table-cell whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                  <%= button_to "Remove", remove_flashcard_user_deck_path(current_user.id, current_user.deck, flashcard_id: deck_flashcard.flashcard.id, deck_flashcard_id: deck_flashcard.id, category: deck_flashcard.category), class: "rounded bg-indigo-600 px-2 py-1 text-xs font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600", aria: {label: "remove"}, data: {confirm: "Are you sure?"},  method: :delete %>
                  <button type="button" class="rounded bg-indigo-600 px-2 py-1 text-xs font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Reset<span class="sr-only">Reset</span></button>
                  
                </div>
              </div>
              <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/decks/_stats_header.html.erb
<div class="overflow-hidden rounded-lg bg-white shadow"  id="stats_header">
  <div class="px-4 py-5 sm:p-6">
    Deck Statistics
  </div>
  <dl class="mx-auto grid grid-cols-1 gap-px bg-gray-900/5 sm:grid-cols-2 lg:grid-cols-4">
    <div class="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-2 bg-white px-4 py-10 sm:px-6 xl:px-8">
      <dt class="text-sm font-medium leading-6 text-gray-500">Total cards</dt>
      <dd class="text-xs font-medium text-gray-700"></dd>
      <dd class="w-full flex-none text-3xl font-medium leading-10 tracking-tight text-gray-900"><%= @categorized_deck_flashcards.size %></dd>
    </div>
    <div class="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-2 bg-white px-4 py-10 sm:px-6 xl:px-8">
      <dt class="text-sm font-medium leading-6 text-gray-500">Total correct</dt>
      <dd class="text-xs font-medium text-rose-600"></dd>
      <dd class="w-full flex-none text-3xl font-medium leading-10 tracking-tight text-gray-900"><%= @categorized_deck_flashcards.total_correct_count %></dd>
    </div>
    <div class="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-2 bg-white px-4 py-10 sm:px-6 xl:px-8">
      <dt class="text-sm font-medium leading-6 text-gray-500">Total incorrect</dt>
      <dd class="text-xs font-medium text-gray-700"></dd>
      <dd class="w-full flex-none text-3xl font-medium leading-10 tracking-tight text-gray-900"><%= @categorized_deck_flashcards.total_incorrect_count  %></dd>
    </div>
    <div class="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-2 bg-white px-4 py-10 sm:px-6 xl:px-8">
      <dt class="text-sm font-medium leading-6 text-gray-500">Accuracy</dt>
      <dd class="text-xs font-medium text-rose-600"></dd>
      <dd class="w-full flex-none text-3xl font-medium leading-10 tracking-tight text-gray-900"><%= (@categorized_deck_flashcards.average_accuracy * 100).round(0) %>%</dd>
    </div>
  </dl>
</div>

app/views/decks/_stats_navbar.html.erb
<div class="px-4 py-5 sm:px-6 flex justify-center gap-3">
  <!-- Content goes here -->
  <!-- We use less vertical padding on card headers on desktop than on body sections -->
  <%= link_to 'All Cards', user_deck_path(current_user.id, @deck), class: user_deck_classes %> <!-- add remote: true ?-->
  <%= link_to 'New Cards', user_deck_path(current_user.id, @deck, category: 'new'), class: user_deck_classes('new') %> <!-- add remote: true ?-->
  <%= link_to 'Learning', user_deck_path(current_user.id, @deck, category: 'learning'), class: user_deck_classes('learning') %> <!-- add remote: true ?-->
  <%= link_to 'Progressing', user_deck_path(current_user.id, @deck, category: 'progressing'), class: user_deck_classes('progressing') %> <!-- add remote: true ?-->
  <%= link_to 'Mastered', user_deck_path(current_user.id, @deck, category: 'mastered'), class: user_deck_classes('mastered') %> <!-- add remote: true ?-->    
</div>

app/views/decks/create.turbo_stream.erb
<!-- This refreshes the flashcard turboframe, at present only serves to update the state of the add and remove buttons for each flashcard. -->
<%= turbo_stream.replace(dom_id(@flashcard)) do%>
  <%= render partial: "flashcards/flashcard", locals: {flashcard: @flashcard} %>
<%end%>

<%= turbo_stream.replace "flash", partial: "layouts/flash" %>

app/views/decks/formcreate.html.erb
  <div class="overflow-hidden rounded-lg bg-white shadow">
    <%= simple_form_for("", url: "", method: :get
        ) do |f| %>
      <div class="flex justify-center gap-2">
        <div>
          <%= f.input :front, label: false, input_html: { placeholder: 'Front...', value: params[:front] } %>
        </div>
        <div>
          <%= f.input :back, label: false, input_html: { placeholder: 'Back...', value: params[:back] } %>
        </div>
        <div class="flex align-center">
          <%= f.button :submit, "Create" %>
        </div>
      </div>
    <% end %>
  </div>

app/views/decks/remove_flashcard.turbo_stream.erb
<%= turbo_stream.replace "flash", partial: "layouts/flash" %>

<%= turbo_stream.replace "stats_header", partial: "decks/stats_header", locals: {
  deck: @deck,
  categorized_deck_flashcards: @categorized_deck_flashcards
} %>

<%= turbo_stream.remove dom_id(@deck_flashcard) %>

app/views/decks/show.html.erb
<%= turbo_frame_tag "deck" do %>
<div class="divide-y divide-gray-200 overflow-hidden rounded-lg bg-white shadow">
  <!-- Category navbar & Flashcard Statistics by Category -->
  <%= render "decks/stats_navbar" %>
  <%= render 'decks/stats_header' %>




  <!-- Statistics displayed for each Flashcard -->
  <div class="px-4 py-5 sm:p-6">
    <!-- Content goes here -->
    <%= render 'decks/stats_body' %>
  </div>
  <!-- end -->
</div>
<% end %>