config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  devise_for :users

  resources :users
  get 'users/:id/account', to: 'users#account'
  resources :flashcards do 
    member do 
      post 'add'
      post 'add_list'
      delete 'remove'
      get 'remove_list'
    end 
    collection do 
      get 'grid'
      get 'list'
      post "bulk"
    end 
  end 

  resources :user do 
    resources :decks do 
      member do 
        post 'add_flashcard'
        delete 'remove_flashcard'
      end 

      collection do 
        get 'check_deck_flashcards'
      end 
      resources :deck_flashcards, only: [:show, :update] do 
        member do
          post :mark_correct
          post :mark_incorrect
        end
      end
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "flashcards#index"

  get 'contact', to: 'contact#show'
end

app/models/deck_flashcard.rb
# == Schema Information
#
# Table name: deck_flashcards
#
#  id              :bigint           not null, primary key
#  accuracy        :float            default(0.0), not null
#  attempts        :integer          default(0), not null
#  category        :string           default("new"), not null
#  correct_count   :integer          default(0), not null
#  incorrect_count :integer          default(0), not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  deck_id         :bigint           not null
#  flashcard_id    :bigint           not null
#
# Indexes
#
#  index_deck_flashcards_on_deck_id                   (deck_id)
#  index_deck_flashcards_on_deck_id_and_flashcard_id  (deck_id,flashcard_id) UNIQUE
#  index_deck_flashcards_on_flashcard_id              (flashcard_id)
#
# Foreign Keys
#
#  fk_rails_...  (deck_id => decks.id)
#  fk_rails_...  (flashcard_id => flashcards.id)
#
class DeckFlashcard < ApplicationRecord
  belongs_to :deck
  belongs_to :flashcard

  validates :correct_count, :incorrect_count, :attempts, 
    presence: true, 
    numericality: { 
      only_integer: true, 
      greater_than_or_equal_to: 0 
  }
  validates :accuracy, 
  presence: true, 
  numericality: {
    only_float: true, 
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 100
  }
  validates :category, presence: true

  before_save :update_deck_flashcard_statistics
  after_save :update_deck_statistics
  after_destroy :update_deck_statistics
  after_create_commit { broadcast_deck_flashcards }
  after_destroy_commit { broadcast_deck_flashcards }

  scope :by_category, -> (category) {category.nil? ? all : where(category: category)}

  def self.flashcard 
    # Change to self.get_flashcard ?
    Flashcard.find_by(self.flashcard_id)
  end 

  # Used for scoped collections eg @categorized_deck_flashcards
  def self.average_accuracy
    total_attempts = self.total_correct_count + self.total_incorrect_count
    return 0.0 if total_attempts.zero? 
    
    accuracy = self.total_correct_count.to_f / total_attempts
    accuracy
  end 

  def self.total_correct_count
    self.sum(:correct_count)
  end

  def self.total_incorrect_count
    self.sum(:incorrect_count)
  end

  private

  def broadcast_deck_flashcards
    @deck = self.deck
    # Initiate a broadcast to a Turbo Stream identified by the name "deck_flashcards"
    broadcast_update_to [@deck, "deck_flashcards"],
    # Specifies the partial view that will be rendered and sent as part of the broadcast.
    partial: "layouts/counter",
    #  local variables to the partial.
    # the collection of deck flashcards (deck.deck_flashcards) associated with the deck of the current 
    locals: { deck: @deck},
    #  specifies the DOM element i
    target: "deck-cards-counter"
  end 

  def update_deck_statistics
    deck = Deck.find_by(id: self.deck_id)
    deck.update_statistics
  end 

  def update_deck_flashcard_statistics
    update_attempts
    update_accuracy
    update_category
  end 

  def update_accuracy
    self.accuracy = attempts.zero? ? 0.0 : (correct_count.to_f / attempts * 100)
  end

  def update_attempts
    self.attempts = correct_count.to_i + incorrect_count.to_i
  end 

  def update_category
    case 
    when attempts > 5 && accuracy >= 90
      self.category = "mastered"
    when attempts > 5 && accuracy > 65
      self.category = "progressing" 
    when attempts > 0 && attempts <= 5 || attempts > 5 && accuracy <= 65
      self.category = "learning"
    when attempts == 0
      self.category = "new" 
    else  
      puts "This should not happen in update_category"
    end
  end
end

app/controllers/deck_flashcards_controller.rb
class DeckFlashcardsController < ApplicationController
  before_action :set_deck, :set_deck_flashcards, :set_deck_flashcard, :set_next_deck_flashcard, :set_previous_deck_flashcard 

  def show
    authorize @deck_flashcard
  end

  def next_flashcard
    authorize @deck_flashcard
    render :show
  end 

  def previous_flashcard
    authorize @deck_flashcard
    render :show
  end 

  def mark_correct
    authorize @deck_flashcard
    @deck_flashcard.increment(:correct_count)

    if @deck_flashcard.valid?
      @deck_flashcard.save
      respond_to do |format|
        format.turbo_stream
        format.html 
      end
    end
  end 

  def mark_incorrect
    authorize @deck_flashcard
    @deck_flashcard.increment(:incorrect_count)

    if @deck_flashcard.save
      respond_to do |format|
        format.turbo_stream
        format.html 
      end
    end
  end 

  def update
  end

  private 
  
  def set_deck
    @deck = Deck.find_by(user_id: params[:user_id])
  end 

  def set_deck_flashcards 
    @deck_flashcards = @deck.deck_flashcards.order(id: :asc)
  end 

  def set_deck_flashcard 
    @deck_flashcard = @deck_flashcards.find_by(id: params[:id]) 
  end 

  def set_next_deck_flashcard
    # Sets the link_to "next" in the study page (deck_flashcards#show)
    next_deck_flashcards = @deck_flashcards.where('id > ?', @deck_flashcard.id)
    
    next_deck_flashcards.empty? ? @next_deck_flashcard = nil : @next_deck_flashcard = next_deck_flashcards.first
  end 

  def set_previous_deck_flashcard
    # Sets the link_to "previous" in the study page
    previous_deck_flashcards = @deck_flashcards.where('id < ?', @deck_flashcard.id)

    previous_deck_flashcards.empty? ? @previous_deck_flashcard = nil : @previous_deck_flashcard = previous_deck_flashcards.last
  end 

end

app/helpers/deck_flashcards_helper.rb
module DeckFlashcardsHelper
end

app/views/deck_flashcards/mark_correct.turbo_stream.erb
<%= turbo_stream.update "correct_count", @deck_flashcard.correct_count %>
<%= turbo_stream.replace "accuracy" do%>
<span id="accuracy"> <%= (@deck_flashcard.accuracy).round(0) %>% </span>
<% end %>

app/views/deck_flashcards/mark_incorrect.turbo_stream.erb
<%= turbo_stream.update "incorrect_count", @deck_flashcard.incorrect_count %>
<%= turbo_stream.replace "accuracy" do%>
<span id="accuracy"> <%= (@deck_flashcard.accuracy).round(0) %>% </span>
<% end %>

app/views/deck_flashcards/show.html.erb
<%= turbo_frame_tag 'flashcard' do%>
  <div class="flex justify-center">
    <a class="bg-gray-800 text-white rounded-l-md border-r border-gray-100 py-2 hover:bg-red-700 hover:text-white px-3" 
    href="
    <%= @previous_deck_flashcard ? user_deck_deck_flashcard_path(current_user, @deck, @previous_deck_flashcard) : "#" %>" data-turbo-action="advance">
      <div>
        <div class="flex flex-row align-middle">
          <svg
            class="w-5 mr-2"
            fill="currentColor"
            viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              fill-rule="evenodd"
              d="M7.707 14.707a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l2.293 2.293a1 1 0 010 1.414z"
              clip-rule="evenodd"
            ></path>
          </svg>
          
          <p class="ml-2">Prev</p>
        </div>
      </div>
    </a>

    
    <section>
      <div id="deck_flashcard_ui" data-controller="studycard" data-action="click->studycard#toggleCard">
        <div data-studycard-target="card" class="block max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
          <div id="front" class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
            <%= @deck_flashcard.flashcard.front %>
            <p class="font-normal text-gray-700 dark:text-gray-400">
              Click to see PT
            </p>
          </div>
          <div id="back" class="hidden mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
            <%= @deck_flashcard.flashcard.back %>
            <p class="font-normal text-gray-700 dark:text-gray-400">
              Phonetics here
            </p>
          </div>
        </div>
      </div>
    </section>
  

    <a class="bg-gray-800 text-white rounded-r-md py-2 border-l border-gray-200 hover:bg-red-700 hover:text-white px-3"
    href="<%= @next_deck_flashcard ? user_deck_deck_flashcard_path(current_user, @deck, @next_deck_flashcard) : "#" %>", data-turbo-action="advance"> 
    
      <div>
        <div class="flex flex-row align-middle">
          <span class="mr-2">Next</span>
          <svg
            class="w-5 ml-2"
            fill="currentColor"
            viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              fill-rule="evenodd"
              d="M12.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-2.293-2.293a1 1 0 010-1.414z"
              clip-rule="evenodd"
            ></path>
          </svg>
        </div>
      </div>
      </a>
  </div>


  <div class="flex justify-center pt-6 gap-2">
    <%= button_to 'Correct', mark_correct_user_deck_deck_flashcard_path(current_user, @deck, @deck_flashcard.id), data: {turbo_stream: true}, method: :post, class: "rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
    <%= button_to 'Incorrect', mark_incorrect_user_deck_deck_flashcard_path(current_user, @deck, @deck_flashcard.id), method: :post, class: "rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
  </div>

  <!-- UPDATE LATER -->

  <div class="flex flex-col items-center justify-center pt-6 gap-2">
    <h2>Stats</h2>
    <div class="flex">
      <div>Correct: <span id="correct_count"><%= @deck_flashcard.correct_count %></span> </div>
      
    </div>
    <div class="flex">
      <div>Incorrect:<span id="incorrect_count"><%= @deck_flashcard.incorrect_count %></span> </div>
    </div>
    <div class="flex">
      <div>Accuracy: <span id="accuracy"> <%= (@deck_flashcard.accuracy).round(0) %>% </span></div>  
    </div>
  </div>


  <!-- UPDATE LATER -->
 <%= link_to 'Details', '#', data: { turbo_frame: "_top"}  %>
<% end %>